/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.ukui.panel.daemon.xml -i server.h -a dbus-adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUS-ADAPTOR_H
#define DBUS-ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "server.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.ukui.panel.daemon
 */
class DaemonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.ukui.panel.daemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.ukui.panel.daemon\">\n"
"    <method name=\"DesktopToWID\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"desktop\"/>\n"
"    </method>\n"
"    <method name=\"WIDToDesktop\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"DesktopFileDeleteSlot\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"deleteFile\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DaemonAdaptor(QObject *parent);
    virtual ~DaemonAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void DesktopFileDeleteSlot(const QString &path, const QStringList &deleteFile);
    int DesktopToWID(const QString &desktop);
    QString WIDToDesktop(int id);
Q_SIGNALS: // SIGNALS
};

#endif
