.TH ukui "1" "2020-01-01" "UKUI 0.10.0" "UKUI Desktop Environment"
.SH NAME
panel-daemon \- Panel background service.
.SH SYNOPSIS
.B panel-daemon
.br
.SH DESCRIPTION
Monitor the operation of taskbar.
.SH BEHAVIOR
Monitor the operation of taskbar.
.P
.SH "REPORTING BUGS"
Report bugs to https://github.com/ukui/ukui-panel/issues
.SH "SEE ALSO"

