.TH ukui "1" "2020-01-01" "UKUI 0.10.0" "UKUI Desktop Environment"
.SH NAME
sni-daemon \- Background service program of SNI protocol.
.SH SYNOPSIS
.B sni-daemon
.br
.SH DESCRIPTION
sni-daemon monitors the registration behavior of the application and registers it in the system tray.
.SH BEHAVIOR
sni-daemon monitors the registration behavior of the application and registers it in the system tray.
.P
.SH "REPORTING BUGS"
Report bugs to https://github.com/ukui/ukui-panel/issues
.SH "SEE ALSO"

