.TH ukui "1" "2020-01-01" "UKUI 0.10.0" "UKUI Desktop Environment"
.SH NAME
ukui-flash-disk \- The Tray Application for the UKUI Desktop Environment
.SH SYNOPSIS
.B ukui-flash-disk
.br
.SH DESCRIPTION
This is  tray application for ukui-panel
.SH BEHAVIOR
Ukui-flash-disk tray application can detect whether there is external storage medium mounted
Click to open the content of the storage medium
.P
Ukui-flash-disk can according to the detected signal to determine whether to display in the tray bar
.SH "REPORTING BUGS"
Report bugs to https://github.com/ukui/ukui-panel/issues
.SH "SEE ALSO"

