.TH ukui "1" "2019-08-01" "UKUI 0.10.0" "UKUI Desktop Panel Module"
.SH NAME
ukui-panel \- The Panel for the UKUI Desktop Environment
.SH SYNOPSIS
.B ukui-panel
.br
.SH DESCRIPTION
This module adds a panel, with optional plugins, to the desktop.
.SH BEHAVIOR
The panel can be run independently of \fBUKUI\fR, autostarted at logon, and have
multiple instances. A horizontal bottom panel shows by default on the desktop,
but the size, autohide, and other attributes 
.P
The panel is comprised of plugins which provide a visual widget; like the startmenu,
taskbar, or quicklaunch. They can be added or removed in the panel Widget settings.
.P
Several plugins are loaded by default; the desktop menu and windows workspaces
are also managed here.
.SH CONFIGURATIONS
Right-click over any plugin to reach the panel Configure settings option, or
that of each respective plugin.
.SH "REPORTING BUGS"
Report bugs to https://github.com/ukui/ukui-panel/issues
.SH "SEE ALSO"
.SS
Ukui Panel documentation can be found under "Help" by right-clicking on \fBukui-panel\fR.
Further information may also be available at: http://wiki.ukui-desktop.org/docs
.P

