/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a singleapplicationadaptor -i common/ukuisingleapplication.h -l UKUi::SingleApplication /home/kylin/work/panel/ukui-panel/panel/common/dbus/org.ukui.SingleApplication.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SINGLEAPPLICATIONADAPTOR_H
#define SINGLEAPPLICATIONADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "common/ukuisingleapplication.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.ukui.SingleApplication
 */
class SingleApplicationAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.ukui.SingleApplication")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.ukui.SingleApplication\">\n"
"    <method name=\"activateWindow\"/>\n"
"  </interface>\n"
        "")
public:
    SingleApplicationAdaptor(UKUi::SingleApplication *parent);
    virtual ~SingleApplicationAdaptor();

    inline UKUi::SingleApplication *parent() const
    { return static_cast<UKUi::SingleApplication *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void activateWindow();
Q_SIGNALS: // SIGNALS
};

#endif
