/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -m -a singleapplicationadaptor -i common/ukuisingleapplication.h -l UKUi::SingleApplication /home/kylin/work/panel/ukui-panel/panel/common/dbus/org.ukui.SingleApplication.xml
 *
 * qdbusxml2cpp is Copyright (C) 2019 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "singleapplicationadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SingleApplicationAdaptor
 */

SingleApplicationAdaptor::SingleApplicationAdaptor(UKUi::SingleApplication *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SingleApplicationAdaptor::~SingleApplicationAdaptor()
{
    // destructor
}

void SingleApplicationAdaptor::activateWindow()
{
    // handle method call org.ukui.SingleApplication.activateWindow
    parent()->activateWindow();
}


#include "singleapplicationadaptor.moc"
