name: build

on:
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout ukui-panel source
      uses: actions/checkout@v2

    - name: Update apt repository
      run: sudo apt-get update -y

    - name: Install latest Qt5
      run: sudo apt-get -y install build-essential qt5-default qttools5-dev-tools

    - name: Instal dependcies
      run: sudo apt-get install -y debhelper-compat cmake libasound2-dev libdbusmenu-qt5-dev libglib2.0-dev libicu-dev libkf5solid-dev libkf5windowsystem-dev libpulse-dev libqt5svg5-dev libqt5x11extras5-dev libsensors4-dev libstatgrab-dev libsysstat-qt5-0-dev libx11-dev libxcb-damage0-dev libxcb-util0-dev libxcb-xkb-dev libxcomposite-dev libxdamage-dev libxkbcommon-dev libxkbcommon-x11-dev libxrender-dev libqt5webkit5-dev qttools5-dev libqt5xdg-dev libgsettings-qt-dev libpoppler-dev libpoppler-qt5-dev libpeony-dev libdconf-dev

    - name: CMake generate & Make
      run: mkdir build && cd build && cmake .. && make -j$(nproc)
  